import React, { useState } from 'react';
import { Input, Button } from 'semantic-ui-react'
import Head from 'next/head'
import Router from 'next/router';
import styles from '../../styles/Home.module.css'
import { isStudentExist } from '../../utils/student-utils';


export default function LoginStudent() {
    const [studentID, setStudentID] = useState(''); // '' is the initial state value

    async function loginAsStudent() {
        if (studentID != '') {
            let exist = await isStudentExist(studentID);
            if (exist) {
                Router.push(`/student/${studentID}`)
            } else {
                alert("Incorrect student credential information to login!")
            }
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Login as a student
                </h1>

                <p className={styles.description}>
                    You will be prompted to enter your <span className={styles.blueColor}>student id</span> in order to login.
                </p>

                <Input value={studentID} onChange={e => setStudentID(e.target.value)} focus placeholder='Enter your student id' />
                <br />
                <Button onClick={loginAsStudent} primary>Login</Button>
            </main>

        </div>
    )
}

