version: "3.9"
services:
  student_db:
    container_name: edufi_student_db
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MYSQL_DATABASE: 'Edufi_Student'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./REST/students/database/:/app
    networks:
      - sub-etha
  
  student_backend:
    container_name: student_microservice
    # Configuration for building the docker image for the service
    build:
      context: ./REST/students/server/ # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    expose:
      # Opens port 8080 on the container
      - '8080'
    volumes:
      - ./REST/students/server:/code
    restart: always
    depends_on:
      - student_db
    networks:
      - sub-etha

  student_acl:
    container_name: student_acl_server
    build:
      context: ./REST/students/acl/
      target: dev
    volumes:
      - ./REST/students/acl/:/app
      - /app/node_modules
    command: npm run start
    expose:
      # Opens port 4000 on the container
      - '4000'
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - student_backend
    networks:
      - sub-etha

volumes:
  node_modules:

networks:
  sub-etha: