import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'
import { getStaticPathForStudents, getStudent } from '../../../utils/student-utils';

export async function getStaticProps({ params }) {
    const studentID = params.id
    const student = await getStudent(studentID, false);

    return {
        props: {
            ...student
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForStudents();

    return {
        paths,
        fallback: false
    }
}

export default function StudentHome({ student_id, name }) {
    let viewParticularsLink = `${student_id}/view`
    let updateParticulasLink = `${student_id}/edit`;
    let viewAllStudentsWithRatingsLink = `${student_id}/view_students`;


    return (
        <div className={styles.container}>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    U are now signed in as <span className={styles.blueColor}> {name}  </span>
                </h1>

                <br />

                <div className={styles.grid}>
                    <Link href={viewParticularsLink}>
                        <a className={styles.card}>
                            <h2>View Particulars &rarr;</h2>
                            <p>View the student's identification number, name, date of birth, address and phone number.</p>
                        </a>
                    </Link>

                    <Link href={updateParticulasLink}>
                        <a className={styles.card}>
                            <h2>Update Particulars &rarr;</h2>
                            <p>Edit the student's particulars including name, date of birth, address and phone number.</p>
                        </a>
                    </Link>

                    <Link href="">
                        <a className={styles.card}>
                            <h2>View modules taken &rarr;</h2>
                            <p>View the modules taken by the student. asdadskadjsk</p>
                        </a>
                    </Link>

                    <Link href="">
                        <a className={styles.card}>
                            <h2>View original results &rarr;</h2>
                            <p>View the original result of the student.</p>
                        </a>
                    </Link>

                    <Link href="">
                        <a className={styles.card}>
                            <h2>View adjusted results after marks trading &rarr;</h2>
                            <p>View the student's adjusted results after marks trading.</p>
                        </a>
                    </Link>

                    <Link href={viewAllStudentsWithRatingsLink}>
                        <a className={styles.card}>
                            <h2>List all students with ratings &rarr;</h2>
                            <p>List all students with ratings.</p>
                        </a>
                    </Link>

                    <Link href="">
                        <a className={styles.card}>
                            <h2>Search for other students &rarr;</h2>
                            <p>Search for other students and view their profile, modules, timetable, ratings, and comments.</p>
                        </a>
                    </Link>

                </div>
            </main>

        </div>
    )
}