import { getModules } from '../../../utils/student-utils';
import React from 'react'
import { Button, Table } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import Head from 'next/head'
import Router from 'next/router';


export async function getServerSideProps({ query }) {
    const student_id = query.id
    const modules = await getModules(student_id);
    console.log(modules)

    return {
        props: {
            student_id,
            modules
        }
    }
}

export default function ViewModules({ student_id, modules }) {

    function backToStudentHome() {
        Router.push(`/student/${student_id}`)
    }

    const rows = modules != null ? modules.map(function (module) {
        return (
            <Table.Row key={module.module_id}>
                <Table.Cell>{module.module_id}</Table.Cell>
                <Table.Cell>{module.module_code}</Table.Cell>
                <Table.Cell>{module.module_name}</Table.Cell>
                <Table.Cell>{module.synopsis}</Table.Cell>
                <Table.Cell>{module.learning_objectives}</Table.Cell>
                <Table.Cell>{module.tutor.last_name + " " + module.tutor.first_name}</Table.Cell>
                <Table.Cell>{module.tutor.email}</Table.Cell>
            </Table.Row>
        )
    }) : 'There are no modules'

    return (

        <div className={styles.container}>
            <Head>
                <title>View modules taken</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                View Modules taken
            </h1>

            <br />

            <Table celled>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>ID</Table.HeaderCell>
                        <Table.HeaderCell>Code</Table.HeaderCell>
                        <Table.HeaderCell>Name</Table.HeaderCell>
                        <Table.HeaderCell>Synopsis</Table.HeaderCell>
                        <Table.HeaderCell>Learning Objectives</Table.HeaderCell>
                        <Table.HeaderCell>Tutor Name</Table.HeaderCell>
                        <Table.HeaderCell>Tutor Email</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {rows}
                </Table.Body>

            </Table>

            <br />
            <Button primary onClick={backToStudentHome} type='submit'>Back To Home</Button>
        </div>
    )
}