import { getTimetables } from '../../../utils/student-utils';
import React from 'react'
import { Button, Table } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import Head from 'next/head'
import Router from 'next/router';


export async function getServerSideProps({ query }) {
    const student_id = query.id
    const results = await getTimetables(student_id);

    return {
        props: {
            student_id,
            results
        }
    }
}

export default function ViewTimetable({ student_id, results }) {

    function backToStudentHome() {
        Router.push(`/student/${student_id}`)
    }

    const rows = results != null ? results.map(function (result) {
        return (
            <Table.Row key={result.lesson_id}>
                <Table.Cell>{result.lesson_id}</Table.Cell>
                <Table.Cell>{result.module.module_code}</Table.Cell>
                <Table.Cell>{result.module.module_name}</Table.Cell>
                <Table.Cell>{result.module.tutor.last_name + " " + result.module.tutor.first_name}</Table.Cell>
                <Table.Cell>{result.module.tutor.email}</Table.Cell>
                <Table.Cell>{result.lesson_day}</Table.Cell>
                <Table.Cell>{result.start_time}</Table.Cell>
                <Table.Cell>{result.end_time}</Table.Cell>
            </Table.Row>
        )
    }) : 'There are no timetable available'

    return (

        <div className={styles.container}>
            <Head>
                <title>View Timetable</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                View Timetable
            </h1>

            <br />

            <Table celled>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>ID</Table.HeaderCell>
                        <Table.HeaderCell>Module Code</Table.HeaderCell>
                        <Table.HeaderCell>Module Name</Table.HeaderCell>
                        <Table.HeaderCell>Tutor Name</Table.HeaderCell>
                        <Table.HeaderCell>Tutor Email</Table.HeaderCell>
                        <Table.HeaderCell>Lesson Day</Table.HeaderCell>
                        <Table.HeaderCell>Start Time</Table.HeaderCell>
                        <Table.HeaderCell>End Time</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {rows}
                </Table.Body>

            </Table>

            <br />
            <Button primary onClick={backToStudentHome} type='submit'>Back To Home</Button>
        </div>
    )
}