import { getStaticPathForStudents, getStudents } from '../../../utils/student-utils';
import React from 'react'
import { Button, Table } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import Head from 'next/head'
import Router from 'next/router';
import { formatDateStringFromMs } from '../../../utils/date-utils';


export async function getStaticProps({ params }) {
    const student_id = params.id
    const students = await getStudents();

    return {
        props: {
            student_id,
            students
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForStudents();

    return {
        paths,
        fallback: false
    }
}

export default function ViewStudents({ student_id, students }) {

    function backToStudentHome() {
        Router.push(`/student/${student_id}`)
    }

    const rows = students != null ? students.map(function (student) {
        return (
            <Table.Row key={student.student_id}>
                <Table.Cell>{student.student_id}</Table.Cell>
                <Table.Cell>{student.name}</Table.Cell>
                <Table.Cell>{student.address}</Table.Cell>
                <Table.Cell>{student.phone_number}</Table.Cell>
                <Table.Cell>{formatDateStringFromMs(parseInt(student.date_of_birth))}</Table.Cell>
            </Table.Row>
        )
    }) : 'There are no students'

    return (

        <div className={styles.container}>
            <Head>
                <title>All students with ratings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                All students with ratings
            </h1>

            <br />

            <Table celled>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>StudentID</Table.HeaderCell>
                        <Table.HeaderCell>Name</Table.HeaderCell>
                        <Table.HeaderCell>Addrress</Table.HeaderCell>
                        <Table.HeaderCell>PhoneNumber</Table.HeaderCell>
                        <Table.HeaderCell>DateOfBirth</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {rows}
                </Table.Body>

            </Table>

            <br />
            <Button primary onClick={backToStudentHome} type='submit'>Back To Home</Button>
        </div>
    )
}