import { getStaticPathForStudents, getStudent } from '../../../utils/student-utils';
import React from 'react'
import { Button, Form } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import Head from 'next/head'
import Router from 'next/router';
import { formatDateStringFromMs } from '../../../utils/date-utils';


export async function getStaticProps({ params }) {
    const studentID = params.id
    const student = await getStudent(studentID, false);

    return {
        props: {
            ...student
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForStudents();

    return {
        paths,
        fallback: false
    }
}

export default function ViewStudent({ student_id, name, phone_number, address, date_of_birth }) {

    async function EditParticulars() {
        Router.push(`/student/${student_id}/edit`)
    }

    function backToStudentHome() {
        Router.push(`/student/${student_id}`)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>View Particulars</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                View Particulars
            </h1>

            <br />

            <Form>
                <Form.Group widths='equal'>
                    <Form.Field>
                        <label>Student ID</label>
                        <div className={styles.solidBorder}> {student_id} </div>

                    </Form.Field>

                    <Form.Field>
                        <label>Name</label>
                        <div className={styles.solidBorder}> {name} </div>
                    </Form.Field>
                </Form.Group>

                <Form.Group widths='equal'>
                    <Form.Field>
                        <label>Address</label>
                        <div className={styles.solidBorder}> {address} </div>
                    </Form.Field>

                    <Form.Field>
                        <label>Date of Birth</label>
                        <div className={styles.solidBorder}> {formatDateStringFromMs(parseInt(date_of_birth))}</div>
                    </Form.Field>
                </Form.Group>

                <Form.Group widths='equal'>

                    <Form.Field>
                        <label>Phone Number</label>
                        <div className={styles.solidBorder}> {phone_number} </div>
                    </Form.Field>
                </Form.Group>

                <Button onClick={EditParticulars} type='submit'>Edit Particulars</Button>
            </Form>

            <br />
            <Button primary onClick={backToStudentHome} type='submit'>Back To Home</Button>
        </div>
    )
}