import { getStudentsWithRatings } from '../../../utils/student-utils';
import React from 'react'
import { Button, Table } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import Head from 'next/head'
import Router from 'next/router';
import { formatDateStringFromMs } from '../../../utils/date-utils';


export async function getServerSideProps({ query }) {
    const student_id = query.id
    const students = await getStudentsWithRatings();

    return {
        props: {
            student_id,
            students
        }
    }
}

export default function ViewStudents({ student_id, students }) {

    function backToStudentHome() {
        Router.push(`/student/${student_id}`)
    }

    function formatRatingsDetails(ratings) {
        // sort the created time in descending order
        ratings.sort((second, first) => first.created_time - second.created_time)

        let result = []
        let index = 1

        for (const rating of ratings) {
            let senderName = rating.is_anonymous ? 'Anonymous User' : `${rating.creator_type} #${rating.creator_id}`

            result.push(`${index}. ${senderName} gave ${rating.rating_score} ratings at ${formatDateStringFromMs(rating.created_time)}.`)
            ++index
        }

        return result
    }

    function formatRatings(ratings) {
        let ratingCount = 0;
        let totalRatings = 0;

        for (const rating of ratings) {
            ratingCount += 1;
            totalRatings += rating.rating_score;
        }

        return totalRatings / ratingCount;
    }

    const rows = students != null ? students.map(function (student) {
        return (
            <Table.Row key={student.student_id}>
                <Table.Cell>{student.student_id}</Table.Cell>
                <Table.Cell>{student.name}</Table.Cell>
                <Table.Cell>{student.address}</Table.Cell>
                <Table.Cell>{student.phone_number}</Table.Cell>
                <Table.Cell>{formatDateStringFromMs(parseInt(student.date_of_birth))}</Table.Cell>
                <Table.Cell>{`${formatRatings(student.ratings)} (${student.ratings.length})`}</Table.Cell>
                <Table.Cell style={{ whiteSpace: "pre-line" }}>{formatRatingsDetails(student.ratings).join("\n\n")}</Table.Cell>
            </Table.Row>
        )
    }) : 'There are no students'

    return (

        <div className={styles.container}>
            <Head>
                <title>All students with ratings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                All students with ratings
            </h1>

            <br />

            <Table celled>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>StudentID</Table.HeaderCell>
                        <Table.HeaderCell>Name</Table.HeaderCell>
                        <Table.HeaderCell>Addrress</Table.HeaderCell>
                        <Table.HeaderCell>PhoneNumber</Table.HeaderCell>
                        <Table.HeaderCell>DateOfBirth</Table.HeaderCell>
                        <Table.HeaderCell>Average Ratings</Table.HeaderCell>
                        <Table.HeaderCell>Ratings Details</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {rows}
                </Table.Body>

            </Table>

            <br />
            <Button primary onClick={backToStudentHome} type='submit'>Back To Home</Button>
        </div>
    )
}