name: "CI: EduFi Integration Testing"

on:
  push:
    branches: 
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Initialise Database with SQL Script
        run : |
          docker exec -i edufi_student_db bash
          mysql -uroot -ppassword Edufi_Student < app/setup.sql
  
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install newman
        run: |
          npm install -g newman

      - name: Test REST API with POSTMAN collection
        run: |
          newman run ./test/Edufi-Student.postman_collection.json -r cli

      # - name: Web Testing
      #   run: docker run --network container:edufi-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/