name: "CI: EduFi Integration Testing"

on:
  push:
    branches: 
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d
  
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install newman
        run: |
          npm install -g newman

      - name: Test REST API with POSTMAN collection
        run: |
          newman run ./test/Edufi-Student.postman_collection.json -r cli
      
      # - if: ${{failure()}}       
      #   name: Create Issues
      #   uses: nashmaniac/create-issue-action@v1.1
      #   with:
      #       title: Build Failed for CI on Push Events
      #       token: ${{secrets.GITHUB_TOKEN}}
      #       assignees: ${{github.actor}}
      #       labels: worflow-failed
      #       body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}  

      # - name: Web Testing
      #   run: docker run --network container:edufi-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/